arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
use-deferred-loading: true
synthetic-package: false
output-dir: lib/src/gen/l10n
enable-escaping: true
header: "// ignore_for_file: constant_identifier_names, public_member_api_docs"
preferred-supported-locales:
  - en